name: Envoys
main: com.perkelle.dev.envoys.Bootstrap
version: 5.9.0
api-version: 1.13
softdepend: [DependencyManager, PlaceholderAPI, WorldEdit, WorldGuard, HolographicDisplays, Multiverse-Core, GriefPrevention]
permissions:
  envoys.*:
    description: Gives access to all envoy commands
    default: op
    children:
      envoys.create: true
      envoys.remove: true
      envoys.refill: true
      envoys.amount: true
      envoys.list: true
      envoys.help: true
      envoys.reload: true
      envoys.savedata: true
      envoys.additem: true
      envoys.giveflare: true
      envoys.currentenvoys: true
      envoys.clearholograms: true
      envoys.edit: true
      envoys.debug: true
      envoys.compass: true
      envoys.stop: true
      envoys.single: true

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.20
  - xyz.xenondevs:particle:1.7.1
  - rhino:js:1.7R2
  - org.json:json:20220924
  - me.lucko:commodore:2.2
  - commons-codec:commons-codec:1.15
  - commons-logging:commons-logging:1.2
  - org.apache.httpcomponents:httpcore:4.4.15
  - org.apache.httpcomponents:httpclient:4.5.13
  - org.apache.httpcomponents:fluent-hc:4.5.13
  - org.apache.commons:commons-math3:3.6.1
  - commons-lang:commons-lang:2.6
